# Generated by Django 4.1.7 on 2023-12-29 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MoodData",
            fields=[
                ("dateposted", models.DateField(default=django.utils.timezone.now)),
                ("description", models.TextField()),
                (
                    "moodtype",
                    models.CharField(
                        choices=[
                            ("Excited", "Excited"),
                            ("Happy", "Happy"),
                            ("Relaxed", "Relaxed"),
                            ("Sad", "Sad"),
                            ("Angry", "Angry"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=17, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
