# Generated by Django 4.1.7 on 2023-12-27 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mood", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mooddata",
            old_name="moodmatrix",
            new_name="moodtype",
        ),
        migrations.AddField(
            model_name="mooddata",
            name="token",
            field=models.CharField(
                default="11200bf0ec7305d1713bf175a9ea07ba", max_length=17
            ),
        ),
        migrations.AlterField(
            model_name="mooddata",
            name="dateposted",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 12, 27, 13, 55, 46, 90277, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
