# Generated by Django 4.1.7 on 2023-12-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mood", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mooddata",
            name="moodtype",
            field=models.CharField(
                choices=[
                    ("Excited", "Excited"),
                    ("Happy", "Happy"),
                    ("Fear", "Fear"),
                    ("Sad", "Sad"),
                    ("Angry", "Angry"),
                ],
                max_length=20,
            ),
        ),
    ]
