# Generated by Django 4.1.7 on 2023-12-28 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mood", "0002_rename_moodmatrix_mooddata_moodtype_mooddata_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mooddata",
            name="id",
        ),
        migrations.AlterField(
            model_name="mooddata",
            name="dateposted",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="mooddata",
            name="token",
            field=models.CharField(
                max_length=17, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
